@@||fonts.gstatic.com^$important
@@||extccp.com^$important
@@||microsoft.com^$important
@@||office.com^$important
@@||office.net^$important
@@||battle.net^$important
@@||steam.com^$important
@@||clients4.google.com^$important
@@||clients2.google.com^$important
@@||s.youtube.com^$important
@@||video-stats.l.google.com^$important
@@||www.googleapis.com^$important
@@||youtubei.googleapis.com^$important
@@||oauthaccountmanager.googleapis.com^$important
@@||android.clients.google.com^$important
@@||reminders-pa.googleapis.com^$important
@@||firestore.googleapis.com^$important
@@||gstaticadssl.l.google.com^$important
@@||googleapis.l.google.com^$important
@@||dl.google.com^$important
@@||redirector.gvt1.com^$important
@@||www.msftncsi.com^$important
@@||www.msftconnecttest.com^$important
@@||outlook.office365.com^$important
@@||products.office.com^$important
@@||c.s-microsoft.com^$important
@@||i.s-microsoft.com^$important
@@||login.live.com^$important
@@||login.microsoftonline.com^$important
@@||g.live.com^$important
@@||dl.delivery.mp.microsoft.com^$important
@@||geo-prod.do.dsp.mp.microsoft.com^$important
@@||displaycatalog.mp.microsoft.com^$important
@@||sls.update.microsoft.com.akadns.net^$important
@@||fe3.delivery.dsp.mp.microsoft.com.nsatc.net^$important
@@||tlu.dl.delivery.mp.microsoft.com^$important
@@||msedge.api.cdp.microsoft.com^$important
@@||clientconfig.passport.net^$important
@@||v10.events.data.microsoft.com^$important
@@||v20.events.data.microsoft.com^$important
@@||client-s.gateway.messenger.live.com^$important
@@||arc.msn.com^$important
@@||activity.windows.com^$important
@@||xbox.ipv6.microsoft.com^$important
@@||device.auth.xboxlive.com^$important
@@||www.msftncsi.com^$important
@@||title.mgt.xboxlive.com^$important
@@||xsts.auth.xboxlive.com^$important
@@||title.auth.xboxlive.com^$important
@@||ctldl.windowsupdate.com^$important
@@||attestation.xboxlive.com^$important
@@||xboxexperiencesprod.experimentation.xboxlive.com^$important
@@||xflight.xboxlive.com^$important
@@||cert.mgt.xboxlive.com^$important
@@||xkms.xboxlive.com^$important
@@||def-vef.xboxlive.com^$important
@@||notify.xboxlive.com^$important
@@||help.ui.xboxlive.com^$important
@@||licensing.xboxlive.com^$important
@@||eds.xboxlive.com^$important
@@||www.xboxlive.com^$important
@@||v10.vortex-win.data.microsoft.com^$important
@@||settings-win.data.microsoft.com^$important
@@||s.gateway.messenger.live.com^$important
@@||client-s.gateway.messenger.live.com^$important
@@||ui.skype.com^$important
@@||pricelist.skype.com^$important
@@||apps.skype.com^$important
@@||m.hotmail.com^$important
@@||sa.symcb.com^$important
@@||s1.symcb.com^$important
@@||s2.symcb.com^$important
@@||s3.symcb.com^$important
@@||s4.symcb.com^$important
@@||s5.symcb.com^$important
@@||officeclient.microsoft.com^$important
@@||dev.virtualearth.net^$important
@@||ecn.dev.virtualearth.net^$important
@@||t0.ssl.ak.dynamic.tiles.virtualearth.net^$important
@@||t0.ssl.ak.tiles.virtualearth.net^$important
@@||itunes.apple.com^$important
@@||s.mzstatic.com^$important
@@||appleid.apple.com^$important
@@||gsp-ssl.ls.apple.com^$important
@@||gsp-ssl.ls-apple.com.akadns.net^$important
@@||connectivitycheck.android.com^$important
@@||android.clients.google.com^$important
@@||clients3.google.com^$important
@@||connectivitycheck.gstatic.com^$important
@@||msftncsi.com^$important
@@||www.msftncsi.com^$important
@@||ipv6.msftncsi.com^$important
@@||captive.apple.com^$important
@@||gsp1.apple.com^$important
@@||www.apple.com^$important
@@||www.appleiphonecell.com^$important
@@||spclient.wg.spotify.com^$important
@@||apresolve.spotify.com^$important
@@||api-tv.spotify.com^$important
@@||upload.facebook.com^$important
@@||creative.ak.fbcdn.net^$important
@@||external-lhr0-1.xx.fbcdn.net^$important
@@||external-lhr1-1.xx.fbcdn.net^$important
@@||external-lhr10-1.xx.fbcdn.net^$important
@@||external-lhr2-1.xx.fbcdn.net^$important
@@||external-lhr3-1.xx.fbcdn.net^$important
@@||external-lhr4-1.xx.fbcdn.net^$important
@@||external-lhr5-1.xx.fbcdn.net^$important
@@||external-lhr6-1.xx.fbcdn.net^$important
@@||external-lhr7-1.xx.fbcdn.net^$important
@@||external-lhr8-1.xx.fbcdn.net^$important
@@||external-lhr9-1.xx.fbcdn.net^$important
@@||fbcdn-creative-a.akamaihd.net^$important
@@||scontent-lhr3-1.xx.fbcdn.net^$important
@@||scontent.xx.fbcdn.net^$important
@@||scontent.fgdl5-1.fna.fbcdn.net^$important
@@||graph.facebook.com^$important
@@||b-graph.facebook.com^$important
@@||connect.facebook.com^$important
@@||cdn.fbsbx.com^$important
@@||api.facebook.com^$important
@@||edge-mqtt.facebook.com^$important
@@||mqtt.c10r.facebook.com^$important
@@||portal.fb.com^$important
@@||star.c10r.facebook.com^$important
@@||star-mini.c10r.facebook.com^$important
@@||b-api.facebook.com^$important
@@||fb.me^$important
@@||bigzipfiles.facebook.com^$important
@@||facebook.com^$important
@@||www.facebook.com^$important
@@||scontent-atl3-1.xx.fbcdn.net^$important
@@||static.xx.fbcdn.net^$important
@@||edge-chat.messenger.com^$important
@@||video.xx.fbcdn.net^$important
@@||external-ort2-1.xx.fbcdn.net^$important
@@||scontent-ort2-1.xx.fbcdn.net^$important
@@||edge-chat.facebook.com^$important
@@||scontent-mia3-1.xx.fbcdn.net^$important
@@||web.facebook.com^$important
@@||rupload.facebook.com^$important
@@||l.messenger.com^$important
@@||www.asadcdn.com^$important
@@||code.bildstatic.de^$important
@@||de.ioam.de^$important
@@||json.bild.de^$important
@@||script.ioam.de^$important
@@||tags.tiqcdn.com^$important
@@||tagger.opecloud.com^$important
@@||image.angebote.spiegel.de^$important
@@||plex.tv^$important
@@||tvdb2.plex.tv^$important
@@||pubsub.plex.bz^$important
@@||proxy.plex.bz^$important
@@||proxy02.pop.ord.plex.bz^$important
@@||cpms.spop10.ams.plex.bz^$important
@@||meta-db-worker02.pop.ric.plex.bz^$important
@@||meta.plex.bz^$important
@@||tvthemes.plexapp.com.cdn.cloudflare.net^$important
@@||tvthemes.plexapp.com^$important
@@||106c06cd218b007d-b1e8a1331f68446599e96a4b46a050f5.ams.plex.services^$important
@@||meta.plex.tv^$important
@@||cpms35.spop10.ams.plex.bz^$important
@@||proxy.plex.tv^$important
@@||metrics.plex.tv^$important
@@||pubsub.plex.tv^$important
@@||status.plex.tv^$important
@@||www.plex.tv^$important
@@||node.plexapp.com^$important
@@||nine.plugins.plexapp.com^$important
@@||staging.plex.tv^$important
@@||app.plex.tv^$important
@@||o1.email.plex.tv^$important
@@||o2.sg0.plex.tv^$important
@@||dashboard.plex.tv^$important
@@||placehold.it^$important
@@||placeholdit.imgix.net^$important
@@||dl.dropboxusercontent.com^$important
@@||ns1.dropbox.com^$important
@@||ns2.dropbox.com^$important
@@||gfwsl.geforce.com^$important
@@||delivery.vidible.tv^$important
@@||img.vidible.tv^$important
@@||videos.vidible.tv^$important
@@||edge.api.brightcove.com^$important
@@||cdn.vidible.tv^$important
@@||v.w-x.co^$important
@@||appspot-preview.l.google.com^$important
@@||tracking.epicgames.com^$important
@@||cloudsync-prod.s3.amazonaws.com^$important
@@||79423.analytics.edgekey.net^$important
@@||telemetry-console.api.playstation.com^$important
@@||styles.redditmedia.com^$important
@@||www.redditstatic.com^$important
@@||reddit.map.fastly.net^$important
@@||www.redditmedia.com^$important
@@||reddit-uploaded-media.s3-accelerate.amazonaws.com^$important
@@||wa.me^$important
@@||www.wa.me^$important
@@||ud-chat.signal.org^$important
@@||chat.signal.org^$important
@@||storage.signal.org^$important
@@||signal.org^$important
@@||www.signal.org^$important
@@||updates2.signal.org^$important
@@||textsecure-service-whispersystems.org^$important
@@||giphy-proxy-production.whispersystems.org^$important
@@||cdn.signal.org^$important
@@||whispersystems-textsecure-attachments.s3-accelerate.amazonaws.com^$important
@@||d83eunklitikj.cloudfront.net^$important
@@||souqcdn.com^$important
@@||cms.souqcdn.com^$important
@@||api.directory.signal.org^$important
@@||contentproxy.signal.org^$important
@@||turn1.whispersystems.org^$important
@@||settings-win.data.microsoft.com^$important
@@||v10.vortex-win.data.microsoft.com^$important
@@||v20.vortex-win.data.microsoft.com^$important
@@||pro.ip-api.com^$important
@@||reports.crashlytics.com^$important
@@||www.google-analytics.com^$important
@@/^whatsapp-cdn-shv-[0-9]{2}-[a-z]{3}[0-9]\.fbcdn\.net$/
@@/^((www|(w[0-9]\.)?web|media((-[a-z]{3}|\.[a-z]{4})[0-9]{1,2}-[0-9](\.|-)(cdn|fna))?)\.)?whatsapp\.(com|net)$/
@@/[a-z]\.thumbs\.redditmedia\.com$/
@@/(\.|^)redd\.it$/
@@/(\.|^)reddit\.com$/
@@||outlook.office365.com^$important
@@||products.office.com^$important
@@||c.s-microsoft.com^$important
@@||i.s-microsoft.com^$important
@@||login.live.com^$important
@@||login.microsoftonline.com^$important
@@||g.live.com^$important
@@||dl.delivery.mp.microsoft.com^$important
@@||geo-prod.do.dsp.mp.microsoft.com^$important
@@||displaycatalog.mp.microsoft.com^$important
@@||s.youtube.com^$important
@@||i.ytimg.com^$important
@@||youtubei.googleapis.com^$important
@@||safebrowsing.googleapis.com^$important
@@||ssl.gstatic.com^$important
@@||fonts.gstatic.com^$important
@@||fonts.googleapis.com^$important
@@||connectivitycheck.gstatic.com^$important
@@||connectivitycheck.android.com^$important
@@||api-global.netflix.com^$important
@@||api-tv.netflix.com^$important
@@||www.recaptcha.net^$important
@@||recaptcha.net^$important
@@||ajax.cloudflare.com^$important
@@||cdnjs.cloudflare.com^$important
@@||whatsapp.net^$important
@@||web.whatsapp.com^$important
@@||mmg.whatsapp.net^$important
@@||media.whatsapp.net^$important
@@||cdn.whatsapp.net^$important
@@||web.whatsapp.com^$important
@@||instagram.com^$important
@@||cdninstagram.com^$important
@@||fbcdn.net^$important
@@||steampowered.com^$important
@@||steamcommunity.com^$important
@@||steamcontent.com^$important
@@||steamgames.com^$important
@@||steamcdn-a.akamaihd.net^$important
@@||content.steampowered.com^$important
@@||media.steampowered.com^$important
@@||epicgames.com^$important
@@||tracking.epicgames.com^$important
@@||fortnite.com^$important
@@||unrealengine.com^$important
@@||xboxlive.com^$important
@@||xbox.com^$important
@@||microsoft.com^$important
@@||login.live.com^$important
@@||sls.update.microsoft.com.akadns.net^$important
@@||dl.delivery.mp.microsoft.com^$important
@@||title.mgt.xboxlive.com^$important
@@||xsts.auth.xboxlive.com^$important
@@||xkms.xboxlive.com^$important
@@||notify.xboxlive.com^$important
@@||ctldl.windowsupdate.com^$important
@@||playstation.com^$important
@@||sonyentertainmentnetwork.com^$important
@@||pscdn.net^$important
@@||psnprofiles.com^$important
@@||api-p013.cdp.playstation.com^$important
@@||telemetry-console.api.playstation.com^$important
@@||gs2.ww.prod.dl.playstation.net^$important
@@||d26xxlqdkhe6ri.cloudfront.net^$important
@@||battle.net^$important
@@||blizzard.com^$important
@@||blzstatic.com^$important
@@||cdn.blizzard.com^$important
@@||blizzard.net^$important
@@||blz-contentstack.com^$important
@@||discordapp.com^$important
@@||discord.com^$important
@@||steamcdn-a.akamaihd.net^$important
@@||akamaihd.net^$important
@@||amazonaws.com^$important
@@||unity.com^$important
@@||playfabapi.com^$important
@@||github.com^$important
@@||rockstargames.com^$important
@@||socialclub.rockstargames.com^$important
@@||rockstargames.com^$important
@@||gtav.net^$important
@@||mpcdn.rockstargames.com^$important
@@||live.rockstargames.com^$important
@@||gtaonline.com^$important
@@||gog.com^$important
@@||gog.eu^$important
@@||gogstatic.com^$important
@@||gog.com^$important
@@||cdn.gog.com^$important
@@||updates.gog.com^$important
@@||gog.com^$important
@@||gogplatform.com^$important
@@||hogwartslegacy.com^$important
@@||wbgames.com^$important
@@||portkeygames.com^$important
@@||hll.legacy.wbgames.com^$important
@@||cloud.rockstargames.com^$important
@@||content.wbgames.com^$important
@@||cdn.wbgames.com^$important
@@||game.wbgames.com^$important
@@||nintendo.com^$important
@@||nintendo.net^$important
@@||nintendo-europe.com^$important
@@||nintendo.co.jp^$important
@@||accounts.nintendo.com^$important
@@||api.lp1.npns.srv.nintendo.net^$important
@@||npns2.c.app.nintendo.net^$important
@@||ecs-lp1.hac.shop.nintendo.net^$important
@@||api-lp1.pctl.srv.nintendo.net^$important
@@||api.lp1.pctl.srv.nintendo.net^$important
@@||push-nofity-lp1.pctl.srv.nintendo.net^$important
@@||aqua.cdn.nintendo.net^$important
@@||sun.hac.lp1.d4c.nintendo.net^$important
@@||cdn-lp1.pctl.srv.nintendo.net^$important
@@||ctest.cdn.nintendo.net^$important
@@||tagaya.baas.nintendo.com^$important
@@||nppl.app.nintendo.net^$important
@@||amazon.com^$important
@@||amazon.de^$important
@@||amazon.co.uk^$important
@@||amazon.fr^$important
@@||amazon.ca^$important
@@||amazon.it^$important
@@||amazon.es^$important
@@||amazon.co.jp^$important
@@||s3.amazonaws.com^$important
@@||d1.amazonaws.com^$important
@@||d2.amazonaws.com^$important
@@||d3.amazonaws.com^$important
@@||api.amazon.com^$important
@@||amazonaws.com^$important
@@||primevideo.com^$important
@@||music.amazon.com^$important
@@||kindle.com^$important
@@||video.amazon.com^$important
@@||amazon.in^$important
@@||x-ray.amazon.com^$important
@@||googlecloud.com^$important
@@||*.googleapis.com^$important
@@||*.gstatic.com^$important
@@||*.cloud.google.com^$important
@@||*.storage.googleapis.com^$important
@@||*.compute.googleapis.com^$important
@@||*.bigquery.googleapis.com^$important
@@||*.firebaseio.com^$important
@@||*.cloudfunctions.net^$important
@@||cloudflare.com^$important
@@||cloudflare.net^$important
@@||*.cloudflare.com^$important
@@||*.cloudflareworkers.com^$important
@@||*.cloudflarestorage.com^$important
@@||*.cdn.cloudflare.net^$important
@@||hetzner.com^$important
@@||*.hetzner.cloud^$important
@@||*.hcloud.io^$important
@@||azure.com^$important
@@||*.azure.com^$important
@@||*.cloudapp.net^$important
@@||*.azurewebsites.net^$important
@@||*.microsoftazure.com^$important
@@||*.msazurecloud.com^$important
@@||entra.microsoft.com^$important
@@||*.entra.microsoft.com^$important
@@||microsoft.com^$important
@@||azure.com^$important
@@||*.azure.com^$important
@@||*.cloudapp.net^$important
@@||*.azurewebsites.net^$important
@@||*.microsoftazure.com^$important
@@||*.msazurecloud.com^$important
@@||office.com^$important
@@||office365.com^$important
@@||outlook.com^$important
@@||*.outlook.com^$important
@@||*.office.com^$important
@@||*.microsoft.com^$important
@@||*.sharepoint.com^$important
@@||*.microsoftonline.com^$important
@@||*.msftauth.net^$important
@@||*.microsoftgraph.com^$important
@@||*.windows.net^$important
@@||*.sqlazurel.com^$important
@@||*.blob.core.windows.net^$important
@@||*.queue.core.windows.net^$important
@@||*.table.core.windows.net^$important
@@||*.cognitive.microsoft.com^$important
@@||*.api.azure.com^$important
@@||fortinet.com^$important
@@||fortiguard.com^$important
@@||fortimail.com^$important
@@||fortinet.net^$important
@@||fortinet.co^$important
@@||forticloud.com^$important
@@||fortiweb.com^$important
@@||fortigate.com^$important
@@||fortisandbox.com^$important
@@||fortilink.com^$important
@@||fortiview.com^$important
@@||fortimanager.com^$important
@@||fortigate.com^$important
@@||fortiswitch.com^$important
@@||fortimailcloud.com^$important
@@||forticlient.com^$important
@@||apple.com^$important
@@||cloudfront.net^$important
@@||icloud.com^$important
@@||apple-dns.net^$important
@@||apple.com^$important
@@||icloud.com^$important
@@||appleid.apple.com^$important
@@||itunes.apple.com^$important
@@||mzstatic.com^$important
@@||apple.co^$important
@@||cdn-apple.com^$important
@@||aaplimg.com^$important
@@||edgesuite.net^$important
@@||me.com^$important
@@||cdn.apple-mapkit.com^$important
@@||icloud-content.com^$important
@@||findmy.com^$important
@@||location.apple.com^$important
@@||wallet.apple.com^$important
@@||time.apple.com^$important
@@||vmware.com^$important
@@||vmwareidentity.com^$important
@@||myvmware.com^$important
@@||cloud.vmware.com^$important
@@||vmwarelearning.com^$important
@@||vrealize.vmware.com^$important
@@||vmwareidentity.cn^$important
@@||air-watch.com^$important
@@||airwatch.com^$important
@@||vmwareidentity.asia^$important
@@||airwatchmdm.com^$important
@@||horizon.vmware.com^$important
@@||sddc.vmware.com^$important
@@||ui.com^$important
@@||unifi.com^$important
@@||unifi-cloud.com^$important
@@||unifi-cloud.net^$important
@@||ubnt.com^$important
@@||community.ui.com^$important
@@||dl.ubnt.com^$important
@@||s3.amazonaws.com/unifi-sdn^$important
@@||dl.ui.com^$important
@@||discovery.ubnt.com^$important
@@||uisp.com^$important
@@||uisp.io^$important
@@||account.ui.com^$important
@@||speed.ui.com^$important
@@||nms.ui.com^$important
@@||telemetry.ubnt.com^$important
@@||elastic.co^$important
@@||cloud.elastic.co^$important
@@||found.no^$important
@@||search-*.es.amazonaws.com^$important
@@||*.search.windows.net^$important
@@||*.azure.elastic-cloud.com^$important
@@||cloud.es.io^$important
@@||es.io^$important
@@||apm.elastic-cloud.com^$important
@@||*.elastic-cloud.com^$important
@@||elastic-cloud.com^$important
@@||elasticsearch.com^$important
@@||eck.elastic.co^$important
@@||kibana.elastic-cloud.com^$important
@@||samsung.com^$important
@@||samsungcloud.com^$important
@@||samsungcloudcdn.com^$important
@@||samsungiotcloud.com^$important
@@||smartthings.com^$important
@@||samsungpushservice.com^$important
@@||galaxyapps.com^$important
@@||samsungknox.com^$important
@@||samsungosp.com^$important
@@||samsungotn.net^$important
@@||cdn.samsungcloudsolution.com^$important
@@||openapi.samsung.com^$important
@@||samsungcloudsolution.com^$important
@@||samsungpay.com^$important
@@||api.samsungpay.com^$important
@@||log-config.samsungacr.com^$important
@@||notice.samsungacr.com^$important
@@||logitech.com^$important
@@||myharmony.com^$important
@@||harmonyremote.com^$important
@@||svcs.myharmony.com^$important
@@||content.dhg.myharmony.com^$important
@@||pubsub.edge.myharmony.com^$important
@@||download01.logitech.com^$important
@@||harmony-api.logitech.com^$important
@@||content.dhg.harmonyremote.com^$important
@@||device.harmonyremote.com^$important
@@||support.logi.com^$important
@@||setup.myharmony.com^$important
@@||googleapis.com^$important
@@||assistant.google.com^$important
@@||firebaseinstallations.googleapis.com^$important
@@||homegraph.googleapis.com^$important
@@||search.googleapis.com^$important
@@||firebaseremoteconfig.googleapis.com^$important
@@||oauth2.googleapis.com^$important
@@||speech.googleapis.com^$important
@@||actions.google.com^$important
@@||voice.google.com^$important
@@||reminders-pa.googleapis.com^$important
@@||connectivitycheck.gstatic.com^$important
@@||clients2.google.com^$important
@@||clients3.google.com^$important
@@||clients4.google.com^$important
@@||play.googleapis.com^$important
@@||android.googleapis.com^$important
@@||www.gstatic.com^$important
@@||translate.googleapis.com^$important
@@||dialogflow.googleapis.com^$important
